# Generated by Django 5.0.6 on 2024-05-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficVolume',
            fields=[

                ('section_id', models.IntegerField(db_column='SECTION_ID',  auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highway', models.IntegerField(db_column='HIGHWAY', default=0)),
                ('section', models.IntegerField(db_column='SECTION', default=0)),
                ('section_length', models.FloatField(
                    db_column='SECTION_LENGTH', default=0.0)),
                ('section_description', models.TextField(
                    db_column='SECTION_DESCRIPTION', default='')),
                ('date', models.TextField(db_column='Date')),
                ('description', models.TextField(
                    db_column='DESCRIPTION', default='')),
                ('group', models.TextField(db_column='GROUP', default='')),
                ('type', models.TextField(db_column='TYPE', default='')),
                ('county', models.TextField(db_column='COUNTY', default='')),
                ('ptrucks', models.TextField(db_column='PTRUCKS', default='')),
                ('adt', models.IntegerField(db_column='ADT', default=0)),
                ('aadt', models.IntegerField(db_column='AADT', default=0)),
                ('direction', models.TextField(db_column='DIRECTION', default='')),
                ('pct85', models.TextField(db_column='85PCT', default='')),
                ('priority_points', models.TextField(
                    db_column='PRIORITY_POINTS', default='')),
            ],
            options={
                'db_table': 'traffic_volumes',
            },
        ),
    ]
